### ISSUE TITLE
Deployment Error 

### ISSUE THREAD

**Issue by Nrgodara** [AbhiModszYT/AnieXEricaMusic#3]
# Unbale to Deploy 
<sup>Traceback (most recent call last):
2024-09-21T14:07:42.774097+00:00 app[worker.1]:   File "<frozen runpy>", line 198, in _run_module_as_main
2024-09-21T14:07:42.774108+00:00 app[worker.1]:   File "<frozen runpy>", line 88, in _run_code
2024-09-21T14:07:42.774108+00:00 app[worker.1]:   File "/app/AnieXEricaMusic/__main__.py", line 62, in <module>
2024-09-21T14:07:42.774211+00:00 app[worker.1]:     asyncio.get_event_loop().run_until_complete(init())
2024-09-21T14:07:42.774256+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
2024-09-21T14:07:42.774407+00:00 app[worker.1]:     return future.result()
2024-09-21T14:07:42.774475+00:00 app[worker.1]:            ^^^^^^^^^^^^^^^
2024-09-21T14:07:42.774485+00:00 app[worker.1]:   File "/app/AnieXEricaMusic/__main__.py", line 41, in init
2024-09-21T14:07:42.774533+00:00 app[worker.1]:     await AMBOT.start()
2024-09-21T14:07:42.774556+00:00 app[worker.1]:   File "/app/AnieXEricaMusic/core/call.py", line 561, in start
2024-09-21T14:07:42.774683+00:00 app[worker.1]:     await self.one.start()
2024-09-21T14:07:42.774706+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/pytgcalls/methods/utilities/start.py", line 35, in start
2024-09-21T14:07:42.774757+00:00 app[worker.1]:     self._env_checker.check_environment()
2024-09-21T14:07:42.774775+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/pytgcalls/environment.py", line 33, in check_environment
2024-09-21T14:07:42.774811+00:00 app[worker.1]:     raise NodeJSNotInstalled(
2024-09-21T14:07:42.774827+00:00 app[worker.1]: pytgcalls.exceptions.NodeJSNotInstalled Please install node (15.0.0+)
2024-09-21T14:07:43.462226+00:00 heroku[worker.1]: Process exited with status 1
2024-09-21T14:07:43.486260+00:00 heroku[worker.1]: State changed from up to crashed</sup>

**Comment by Vivekkumar-IN** [comment]
Look like your **node** is not installed 

**Install Node js by** : `curl -fssL https://deb.nodesource.com/setup_19.x | sudo -E bash - && sudo apt-get install nodejs -y && npm i -g npm`
